### ISSUE TITLE
[Bug] core的login()无法使用

### ISSUE THREAD

**Issue by RX-105** [Fatpandac/fuck_cqooc#10]
core.py中login()解析nonce_res.text时抛出异常。
请求得到的nonce_res是一个403响应，其中text内容是个html页面。我猜有可能是登陆方式变了。

异常信息如下：
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-3-f0c6e898226f> in <module>
----> 1 c.login()

c:\ ...\fuck_cqooc\src\core.py in login(self)
     34         nonce_res = self.__request.do_get(self.__api_url.get_nonce_api())
     35         print(nonce_res.text)
---> 36         data = json.loads(nonce_res.text)
     37         cn = test.cnonce()
     38         hash = test.getEncodePwd(

c:\Users\ ...\AppData\Local\Programs\Python\Python39\lib\json\__init__.py in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    344             parse_int is None and parse_float is None and
    345             parse_constant is None and object_pairs_hook is None and not kw):
--> 346         return _default_decoder.decode(s)
    347     if cls is None:
    348         cls = JSONDecoder

c:\Users\ ...\AppData\Local\Programs\Python\Python39\lib\json\decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

c:\Users\ ...\AppData\Local\Programs\Python\Python39\lib\json\decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Fatpandac** [comment]
反爬更新，已在[e45fe80](https://github.com/Fatpandac/fuck_cqooc/commit/e45fe80262eb198b02c91f1cb05478f3adfbdcfd)修复
