### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by HYMlaile** [Fatpandac/fuck_cqooc#14]
File "ui\dashboardRoot.py", line 208, in login
  File "src\core.py", line 59, in login
  File "src\core.py", line 30, in __process_user_info

**Comment by Fatpandac** [comment]
很开心看你的 issues，不过你的 issues 中信息较少我无法定位问题，你能否提供更加详细的报错信息，以及复现的操作步骤吗？

**Comment by HYMlaile** [comment]
我就正常登陆，然后就直接弹了这个，我去官网看了一下，可能是现在直接增加了验证码造成的

**Comment by HYMlaile** [comment]
> 很开心看你的 issues，不过你的 issues 中信息较少我无法定位问题，你能否提供更加详细的报错信息，以及复现的操作步骤吗？

我就正常登陆，然后就直接弹了这个，我去官网看了一下，可能是现在直接增加了验证码造成的

**Comment by Fatpandac** [comment]
我使用我的帐号可以正常登录，我无法在我本地复现你的问题，
如果你方便的话可否发送你的帐号密码到我邮箱 i@fatpandac.com

**Comment by HYMlaile** [comment]
> 我使用我的帐号可以正常登录，我无法在我本地复现你的问题， 如果你方便的话可否发送你的帐号密码到我邮箱 [i@fatpandac.com](mailto:i@fatpandac.com)

已发送

**Comment by Fatpandac** [comment]
感谢你提供的测试帐号。
问题已经找到，我们会尽快修复，如果急需使用可以尝试为你的帐号添加头像后再次尝试登录。

**Comment by HYMlaile** [comment]
> 感谢你提供的测试帐号。 问题已经找到，我们会尽快修复，如果急需使用可以尝试为你的帐号添加头像后再次尝试登录。

好的，感谢大佬

**Comment by Fatpandac** [comment]
> 好的，感谢大佬

记得更换帐号密码哟
