### ISSUE TITLE
测验自动作答

### ISSUE THREAD

**Issue by abai2020** [Fatpandac/fuck_cqooc#25]
### 这是一个什么样的功能？

测验自动作答

### 这个功能可以解决什么问题？

解决一些没必要的问题

### 这不是重复的功能请求

- [X] 我已经搜索了[现有 issue](https://github.com/Fatpandac/fuck_cqooc/issues)，以确保这项功能尚未被请求。

**Comment by Fatpandac** [comment]
cc @RX-105

**Comment by RX-105** [comment]
你好，感谢你提出的issue。
你希望程序可以自动完成测试。我们认为，这个功能**需要充足的题库**作为支撑，但是我们目前没有。因此，我们暂时不会实现这个功能。
我们以后会寻找可行的其他方案，以求未来实现这个功能。感谢你对本项目的支持。

**Comment by abai2020** [comment]
好的，感谢

**Comment by RX-105** [comment]
已将该issue标记为won't fix
